/**
 * veo_extension source contract — measured against the live API on 2026-09-06.
 *
 * The Gemini API extends the copy it still holds on its own server, addressed by the
 * Files API uri from the generation response. It refuses the bytes of the local file:
 * inline base64 comes back as `400 encodedVideo isn't supported by this model`, and
 * re-uploading the downloaded mp4 comes back as "Input video must be a video that was
 * generated by VEO that has been processed". So a clip with no live handle cannot be
 * extended at all, and the tool has to say that instead of spending the call.
 *
 * No API is called — every case here returns before the request is built.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

// the key is read at import time and extendVideo demands one before it validates anything
process.env.GEMINI_API_KEY ||= 'veo-extension-test-key';
const { extendVideo, videoExtensionSchema } = await import('../dist/video-client.js');
const { TOOLS } = await import('../dist/tools.js');

const FILES_URI = 'https://generativelanguage.googleapis.com/v1beta/files/abc123:download?alt=media';

/** A source mp4 on disk, with the handle beside it when one is given. */
function sourceVideo(handle) {
  const dir = mkdtempSync(join(tmpdir(), 'veo-ext-'));
  const videoPath = join(dir, 'a-8s.mp4');
  writeFileSync(videoPath, 'not a real mp4');
  if (handle) writeFileSync(`${videoPath}.veo.json`, JSON.stringify(handle));
  return videoPath;
}

test('a source uri must be a Files API uri, and is optional', () => {
  const base = { prompt: 'the camera pulls back', sourceVideoPath: '/tmp/a.mp4' };
  assert.equal(videoExtensionSchema.parse(base).sourceVideoUri, undefined);
  assert.equal(videoExtensionSchema.parse({ ...base, sourceVideoUri: FILES_URI }).sourceVideoUri, FILES_URI);
  // a gs:// bucket and a bare file id are both rejected by the API, so they never leave here
  for (const uri of ['gs://bucket/a.mp4', 'files/abc123', 'https://example.com/a.mp4']) {
    assert.equal(videoExtensionSchema.safeParse({ ...base, sourceVideoUri: uri }).success, false, `${uri} should not parse`);
  }
});

test('the tool exposes the uri inlet and tells callers the local file is not the input', () => {
  const tool = TOOLS.find((t) => t.name === 'veo_extension');
  assert.ok(tool.inputSchema.properties.sourceVideoUri, 'no sourceVideoUri inlet');
  assert.deepEqual(tool.inputSchema.required, ['prompt', 'sourceVideoPath']);
  assert.match(tool.description, /48 hours/);
});

test('no handle beside the video is refused before the call', async () => {
  const result = await extendVideo(videoExtensionSchema.parse({
    prompt: 'the camera pulls back',
    sourceVideoPath: sourceVideo(),
  }));
  assert.equal(result.success, false);
  assert.match(result.error, /No Veo file handle/);
  assert.match(result.error, /\.veo\.json/);
});

test('a handle older than the 48-hour retention is refused before the call', async () => {
  const savedAt = new Date(Date.now() - 49 * 60 * 60 * 1000).toISOString();
  const result = await extendVideo(videoExtensionSchema.parse({
    prompt: 'the camera pulls back',
    sourceVideoPath: sourceVideo({ uri: FILES_URI, operation: 'models/veo/operations/x', savedAt }),
  }));
  assert.equal(result.success, false);
  assert.match(result.error, /48 hours/);
});

test('a handle that is not a Files API uri counts as no handle', async () => {
  const result = await extendVideo(videoExtensionSchema.parse({
    prompt: 'the camera pulls back',
    sourceVideoPath: sourceVideo({ uri: 'gs://bucket/a.mp4', operation: 'x', savedAt: new Date().toISOString() }),
  }));
  assert.equal(result.success, false);
  assert.match(result.error, /No Veo file handle/);
});

test('a missing source file is still caught first', async () => {
  const result = await extendVideo(videoExtensionSchema.parse({
    prompt: 'the camera pulls back',
    sourceVideoPath: join(tmpdir(), 'veo-ext-absent', 'nope.mp4'),
    sourceVideoUri: FILES_URI,
  }));
  assert.equal(result.success, false);
  assert.match(result.error, /Source video not found/);
});
