/**
 * veo_extension source contract — measured against the live API on 2026-09-06.
 *
 * The Gemini API extends the copy it still holds on its own server, addressed by the
 * Files API uri from the generation response. It refuses the bytes of the local file:
 * inline base64 comes back as `400 encodedVideo isn't supported by this model`, and
 * re-uploading the downloaded mp4 comes back as "Input video must be a video that was
 * generated by VEO that has been processed". So a clip with no live handle cannot be
 * extended at all, and the tool has to say that instead of spending the call.
 *
 * Nothing here touches the network: the cases that refuse a clip return before the request is
 * built, and the ones that go through stub `fetch` and read the request the SDK produced.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

// the key is read at import time and extendVideo demands one before it validates anything
process.env.GEMINI_API_KEY ||= 'veo-extension-test-key';
const { extendVideo, videoExtensionSchema } = await import('../dist/video-client.js');
const { TOOLS } = await import('../dist/tools.js');

const FILES_URI = 'https://generativelanguage.googleapis.com/v1beta/files/abc123:download?alt=media';
const OTHER_URI = 'https://generativelanguage.googleapis.com/v1beta/files/explicit9:download?alt=media';
const RESULT_URI = 'https://generativelanguage.googleapis.com/v1beta/files/extended7:download?alt=media';
const OPERATION = 'models/veo-3.1-fast-generate-preview/operations/test-op';

const freshHandle = (uri = FILES_URI) => ({ uri, operation: 'models/veo/operations/first', savedAt: new Date().toISOString() });

function jsonResponse(body) {
  return new Response(JSON.stringify(body), { status: 200, headers: { 'content-type': 'application/json' } });
}

/**
 * Answer the three requests a successful extension makes — start, poll, download — and keep
 * what was asked. `setTimeout` is shortened because the poll loop waits 10s before its first
 * look and the answer is already sitting here.
 */
function stubNetwork({ videoUri = RESULT_URI } = {}) {
  const calls = [];
  const origFetch = globalThis.fetch;
  const origSetTimeout = globalThis.setTimeout;

  globalThis.setTimeout = (fn, _ms, ...args) => origSetTimeout(fn, 0, ...args);
  globalThis.fetch = async (input, init = {}) => {
    const url = typeof input === 'string' ? input : input.url;
    calls.push({ url, body: typeof init.body === 'string' ? JSON.parse(init.body) : undefined });

    if (url.endsWith(':predictLongRunning')) return jsonResponse({ name: OPERATION });
    if (url.endsWith(OPERATION)) {
      return jsonResponse({ done: true, response: { generateVideoResponse: { generatedSamples: [{ video: { uri: videoUri } }] } } });
    }
    if (url === videoUri) return new Response(new Uint8Array([0, 0, 0, 32]), { status: 200 });
    throw new Error(`unexpected request: ${url}`);
  };

  return {
    calls,
    get startRequest() {
      const start = calls.find((call) => call.url.endsWith(':predictLongRunning'));
      assert.ok(start, 'the extension never reached the API');
      return start.body;
    },
    restore() {
      globalThis.fetch = origFetch;
      globalThis.setTimeout = origSetTimeout;
    },
  };
}

/** Run one extension against the stub and hand back the result plus what went over the wire. */
async function extendWithStub(request, options) {
  const net = stubNetwork(options);
  try {
    return { result: await extendVideo(videoExtensionSchema.parse(request)), net };
  } finally {
    net.restore();
  }
}

/** A source mp4 on disk, with the handle beside it when one is given. */
function sourceVideo(handle) {
  const dir = mkdtempSync(join(tmpdir(), 'veo-ext-'));
  const videoPath = join(dir, 'a-8s.mp4');
  writeFileSync(videoPath, 'not a real mp4');
  if (handle) writeFileSync(`${videoPath}.veo.json`, JSON.stringify(handle));
  return videoPath;
}

test('a source uri must be a Files API uri, and is optional', () => {
  const base = { prompt: 'the camera pulls back', sourceVideoPath: '/tmp/a.mp4' };
  assert.equal(videoExtensionSchema.parse(base).sourceVideoUri, undefined);
  assert.equal(videoExtensionSchema.parse({ ...base, sourceVideoUri: FILES_URI }).sourceVideoUri, FILES_URI);
  // a gs:// bucket and a bare file id are both rejected by the API, so they never leave here
  for (const uri of ['gs://bucket/a.mp4', 'files/abc123', 'https://example.com/a.mp4']) {
    assert.equal(videoExtensionSchema.safeParse({ ...base, sourceVideoUri: uri }).success, false, `${uri} should not parse`);
  }
});

test('the tool exposes the uri inlet and tells callers the local file is not the input', () => {
  const tool = TOOLS.find((t) => t.name === 'veo_extension');
  assert.ok(tool.inputSchema.properties.sourceVideoUri, 'no sourceVideoUri inlet');
  assert.deepEqual(tool.inputSchema.required, ['prompt', 'sourceVideoPath']);
  assert.match(tool.description, /48 hours/);
});

test('no handle beside the video is refused before the call', async () => {
  const result = await extendVideo(videoExtensionSchema.parse({
    prompt: 'the camera pulls back',
    sourceVideoPath: sourceVideo(),
  }));
  assert.equal(result.success, false);
  assert.match(result.error, /No Veo file handle/);
  assert.match(result.error, /\.veo\.json/);
});

test('a handle older than the 48-hour retention is refused before the call', async () => {
  const savedAt = new Date(Date.now() - 49 * 60 * 60 * 1000).toISOString();
  const result = await extendVideo(videoExtensionSchema.parse({
    prompt: 'the camera pulls back',
    sourceVideoPath: sourceVideo({ uri: FILES_URI, operation: 'models/veo/operations/x', savedAt }),
  }));
  assert.equal(result.success, false);
  assert.match(result.error, /48 hours/);
});

test('a handle that is not a Files API uri counts as no handle', async () => {
  const result = await extendVideo(videoExtensionSchema.parse({
    prompt: 'the camera pulls back',
    sourceVideoPath: sourceVideo({ uri: 'gs://bucket/a.mp4', operation: 'x', savedAt: new Date().toISOString() }),
  }));
  assert.equal(result.success, false);
  assert.match(result.error, /No Veo file handle/);
});

test('a missing source file is still caught first', async () => {
  const result = await extendVideo(videoExtensionSchema.parse({
    prompt: 'the camera pulls back',
    sourceVideoPath: join(tmpdir(), 'veo-ext-absent', 'nope.mp4'),
    sourceVideoUri: FILES_URI,
  }));
  assert.equal(result.success, false);
  assert.match(result.error, /Source video not found/);
});

test('the request carries the handle uri and none of the local bytes', async () => {
  const outputPath = mkdtempSync(join(tmpdir(), 'veo-ext-out-'));
  const { result, net } = await extendWithStub({
    prompt: 'the camera pulls back',
    sourceVideoPath: sourceVideo(freshHandle()),
    outputPath,
    filename: 'extended.mp4',
  });

  assert.equal(result.error, undefined);
  assert.equal(result.success, true);

  // the whole point of the fix: the video field is the server-side handle, nothing else
  const instance = net.startRequest.instances[0];
  assert.deepEqual(instance.video, { uri: FILES_URI });
  const wire = JSON.stringify(net.startRequest);
  for (const refused of ['encodedVideo', 'videoBytes', 'mimeType', 'encoding']) {
    assert.equal(wire.includes(refused), false, `the request still carries ${refused}`);
  }
});

test('the extended clip is saved with a handle of its own', async () => {
  const outputPath = mkdtempSync(join(tmpdir(), 'veo-ext-out-'));
  const before = Date.now();
  const { result } = await extendWithStub({
    prompt: 'the camera pulls back',
    sourceVideoPath: sourceVideo(freshHandle()),
    outputPath,
    filename: 'extended.mp4',
  });

  assert.equal(result.success, true);
  assert.equal(result.videoPath, join(outputPath, 'extended.mp4'));

  // without this the extension of an extension has nothing to address, and the uri is gone for good
  const handle = JSON.parse(readFileSync(`${result.videoPath}.veo.json`, 'utf8'));
  assert.equal(handle.uri, RESULT_URI);
  assert.equal(handle.operation, OPERATION);
  assert.ok(Date.parse(handle.savedAt) >= before, `savedAt ${handle.savedAt} predates the call`);
});

test('an explicit sourceVideoUri overrides the handle beside the file', async () => {
  const expired = { uri: FILES_URI, operation: 'models/veo/operations/old', savedAt: new Date(Date.now() - 49 * 60 * 60 * 1000).toISOString() };
  const { result, net } = await extendWithStub({
    prompt: 'the camera pulls back',
    sourceVideoPath: sourceVideo(expired),
    sourceVideoUri: OTHER_URI,
    outputPath: mkdtempSync(join(tmpdir(), 'veo-ext-out-')),
    filename: 'extended.mp4',
  });

  // the caller's uri is used, and the expiry of the handle it replaced does not block the call
  assert.equal(result.success, true);
  assert.deepEqual(net.startRequest.instances[0].video, { uri: OTHER_URI });
});

test('a handle with an unreadable savedAt is refused before the call', async () => {
  for (const savedAt of ['not a date', undefined]) {
    const result = await extendVideo(videoExtensionSchema.parse({
      prompt: 'the camera pulls back',
      sourceVideoPath: sourceVideo({ uri: FILES_URI, operation: 'models/veo/operations/x', savedAt }),
    }));
    // NaN comparisons are all false, so an unchecked savedAt would send the request instead
    assert.equal(result.success, false, `savedAt ${JSON.stringify(savedAt)} should not reach the API`);
    assert.match(result.error, /no readable savedAt/);
  }
});
